


GAME_WIDTH = 300
GAME_HEIGHT = 600
BLOCK_SIZE = 30
PADDING = 20
SIDE_WIDTH = 200
SIDE_HEIGHT_FRACTION = 0.3

GAME_OVER_WIDTH = 200
SIDE_BAR_FRACTION = 0.3
GAME_OVER_HEIGHT = int(SIDE_BAR_FRACTION * GAME_HEIGHT)
MENU_WIDTH = 200
MENU_HEIGHT = int(0.25 * GAME_HEIGHT)
SCORE_HEIGHT = int(0.3 * GAME_HEIGHT)